# Generated by Django 5.1.3 on 2024-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammersite', '0002_customuser_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activate_invite_code',
            field=models.BooleanField(default=False),
        ),
    ]
